import {faker} from '@faker-js/faker';

export const myChildrenList = [
  {
    id: 100,
    name: 'Jake Smith',
    email: 'jakesmith@gmail.com',
    address: 'Calgary, AB',
    parentName: 'John Smith',
    parentEmail: 'johndSmith@gmail.com',
  },
  {
    id: 101,
    name: 'Cat Smith',
    email: 'catsmith@gmail.com',
    address: 'Calgary, AB',
    parentName: 'John Smith',
    parentEmail: 'johndSmith@gmail.com',
  },
  {
    id: 102,
    name: 'Fish Smith',
    email: 'fishsmith@gmail.com',
    address: 'Calgary, AB',
    parentName: 'John Smith',
    parentEmail: 'johndSmith@gmail.com',
  },
];

export const randomChildInfo = {
  id: faker.number.int({min: 1000, max: 100000}),
  name: faker.person.fullName(),
  email: faker.internet.email(),
  address: faker.location.streetAddress({ useFullAddress: true }),
  parentName: faker.person.fullName(),
  parentEmail: faker.internet.email(),
};

export const programList = [
  {
    id: faker.number.int({min: 1000, max: 100000}),
    name: 'Program A',
    description: 'Description of the program',
    year: 2025,
    season: 'summer',
    start_date: '2025--5-01',
    end_date: '2025-07-31',
    teacher_id: 100,
    number_of_student: 20,
    tuition: 1000.00,
    tuition_discount: 50.00,
    tech_fee: 200.00,
    create_at: Date.now(),
    update_at: Date.now(),
  },
  {
    id: faker.number.int({min: 1000, max: 100000}),
    name: 'Program B',
    description: 'Description of the program',
    year: 2025,
    season: 'fall',
    start_date: '2025--5-03',
    end_date: '2025-10-29',
    teacher_id: 100,
    number_of_student: 20,
    tuition: 1100.00,
    tuition_discount: 50.00,
    tech_fee: 220.00,
    create_at: Date.now(),
    update_at: Date.now(),
  },
  {
    id: faker.number.int({min: 1000, max: 100000}),
    name: 'Program C',
    description: 'Description of the program',
    year: 2025,
    season: 'winter',
    start_date: '2025--11-02',
    end_date: '2026-01-30',
    teacher_id: 100,
    number_of_student: 20,
    tuition: 1200.00,
    tuition_discount: 50.00,
    tech_fee: 250.00,
    create_at: Date.now(),
    update_at: Date.now(),
  }
];

export const activityList = [
  {
    id: faker.number.int({min: 1000, max: 100000}),
    name: 'Activity A',
    description: 'Description of the activity',
    year: 2025,
    season: 'summer',
    start_date: '2025--5-01',
    end_date: '2025-07-31',
    teacher_id: 100,
    number_of_student: 20,
    fee: 300,
    create_at: Date.now(),
    update_at: Date.now(),
  },
  {
    id: faker.number.int({min: 1000, max: 100000}),
    name: 'Activity B',
    description: 'Description of the activity',
    year: 2025,
    season: 'fall',
    start_date: '2025--5-03',
    end_date: '2025-10-29',
    teacher_id: 100,
    number_of_student: 20,
    fee: 350,
    create_at: Date.now(),
    update_at: Date.now(),
  },
  {
    id: faker.number.int({min: 1000, max: 100000}),
    name: 'Activity C',
    description: 'Description of the activity',
    year: 2025,
    season: 'winter',
    start_date: '2025--11-02',
    end_date: '2026-01-30',
    teacher_id: 100,
    number_of_student: 20,
    fee: 400,
    create_at: Date.now(),
    update_at: Date.now(),
  }
];

export const tuitionList = [
  {
    id: faker.number.int({min: 1000, max: 100000}),
    parent_id: faker.number.int({min: 1000, max: 100000}),
    parent: {
      id: faker.number.int({min: 1000, max: 100000}),
      username: 'Parent Smith',
      email: 'parentsmith@gmail.com',
      role: 'parent',
      enabled: true,
    },
    student_id: faker.number.int({min: 1000, max: 100000}),
    student: {
      id: faker.number.int({min: 1000, max: 100000}),
      name: 'Student Smith',
      email: 'studentsmith@gmail.com',
      address: 'Calgary, AB',
      parentName: 'Parent Smith',
      parentEmail: 'parentsmith@gmail.com',
    },
    program_id: faker.number.int({min: 1000, max: 100000}),
    program: {
      id: faker.number.int({min: 1000, max: 100000}),
      name: 'Program A',
      description: 'Description of the program',
      year: 2025,
      season: 'summer',
      start_date: '2025--5-01',
      end_date: '2025-07-31',
      teacher_id: 100,
      number_of_student: 20,
      tuition: 1000.00,
      tuition_discount: 50.00,
      tech_fee: 200.00,
      create_at: Date.now(),
      update_at: Date.now(),
    },
    activities: [
      {
        id: faker.number.int({min: 1000, max: 100000}),
        name: 'Activity A',
        description: 'Description of the activity',
        year: 2025,
        season: 'summer',
        start_date: '2025--5-01',
        end_date: '2025-07-31',
        teacher_id: 100,
        number_of_student: 20,
        fee: 300.00,
        create_at: Date.now(),
        update_at: Date.now(),
      }
    ],
    tuition: 1000.00,
    tuition_discount: 50.00,
    tech_fee: 200.00,
    activities_fee: 300.00,
    total_fee: 1450.00,
    status: 'Done',
    create_at: Date.now(),
    update_at: Date.now(),
  },
  {
    id: faker.number.int({min: 1000, max: 100000}),
    parent_id: faker.number.int({min: 1000, max: 100000}),
    parent: {
      id: faker.number.int({min: 1000, max: 100000}),
      username: 'Parent Smith',
      email: 'parentsmith@gmail.com',
      role: 'parent',
      enabled: true,
    },
    student_id: faker.number.int({min: 1000, max: 100000}),
    student: {
      id: faker.number.int({min: 1000, max: 100000}),
      name: 'Student Smith',
      email: 'studentsmith@gmail.com',
      address: 'Calgary, AB',
      parentName: 'Parent Smith',
      parentEmail: 'parentsmith@gmail.com',
    },
    program_id: faker.number.int({min: 1000, max: 100000}),
    program: {
      id: faker.number.int({min: 1000, max: 100000}),
      name: 'Program B',
      description: 'Description of the program',
      year: 2025,
      season: 'summer',
      start_date: '2025--5-01',
      end_date: '2025-07-31',
      teacher_id: 100,
      number_of_student: 20,
      tuition: 1000.00,
      tuition_discount: 50.00,
      tech_fee: 200.00,
      create_at: Date.now(),
      update_at: Date.now(),
    },
    activities: [
      {
        id: faker.number.int({min: 1000, max: 100000}),
        name: 'Activity B',
        description: 'Description of the activity',
        year: 2025,
        season: 'summer',
        start_date: '2025--5-01',
        end_date: '2025-07-31',
        teacher_id: 100,
        number_of_student: 20,
        fee: 300.00,
        create_at: Date.now(),
        update_at: Date.now(),
      }
    ],
    tuition: 1000.00,
    tuition_discount: 50.00,
    tech_fee: 200.00,
    activities_fee: 300.00,
    total_fee: 1450.00,
    status: 'Progress',
    create_at: Date.now(),
    update_at: Date.now(),
  }
];
